"""SAP Data Dictionary Explorer. Decipher cryptic SAP column names to something more descriptive."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/11_deSAPher.ipynb.

# %% auto #0
__all__ = ['sap_to_pandas_dtype', 'get_sap_table_structure', 'get_sap_table_url', 'get_sap_tables_structure',
           'get_sap_table_description', 'convert_sap_types', 'rename_sap_columns']

# %% ../nbs/11_deSAPher.ipynb #ce7b0158
from .core import *
import httpx
from bs4 import BeautifulSoup
import pandas as pd

# %% ../nbs/11_deSAPher.ipynb #54659ed4
def get_sap_table_structure(url):
    """
    Scrapes SAP table structure from sapdatasheet.org and returns a pandas DataFrame
    """
    import httpx
    from bs4 import BeautifulSoup
    import pandas as pd
    
    response = httpx.get(url)
    soup = BeautifulSoup(response.text, 'lxml')
    
    table = soup.find('table', class_='table table-sm')
    headers = [th.text.strip() for th in table.find('thead').find_all('th')]
    
    rows = []
    for tr in table.find('tbody').find_all('tr'):
        row = [td.text.strip() for td in tr.find_all('td')]
        rows.append(row)
        
    return pd.DataFrame(rows, columns=headers)

# %% ../nbs/11_deSAPher.ipynb #f97f9631
def get_sap_table_url(table_name):
    """
    Constructs sapdatasheet.org URL from SAP table name
    """
    return f'https://www.sapdatasheet.org/abap/tabl/{table_name.lower()}.html'

# %% ../nbs/11_deSAPher.ipynb #a724f2d9
def get_sap_tables_structure(tables):
    """ Gets structure for multiple SAP tables and combines them into one DataFrame with a column indicating the source table """
    dfs = []
    for table in tables:
        url = get_sap_table_url(table)
        df = get_sap_table_structure(url)
        df['Table'] = table
        dfs.append(df)
    
    return pd.concat(dfs, ignore_index=True)

# %% ../nbs/11_deSAPher.ipynb #ef879f9b
def get_sap_table_structure(url):
    """
    Scrapes SAP table structure from sapdatasheet.org and returns a pandas DataFrame
    Returns None if table not found or other error occurs
    """
    try:
        import httpx
        from bs4 import BeautifulSoup
        import pandas as pd
        
        response = httpx.get(url)
        response.raise_for_status()  # Raise error for bad status codes
        
        soup = BeautifulSoup(response.text, 'lxml')
        table = soup.find('table', class_='table table-sm')
        
        if table is None:
            print(f"No table found at {url}")
            return None
            
        headers = [th.text.strip() for th in table.find('thead').find_all('th')]
        
        rows = []
        for tr in table.find('tbody').find_all('tr'):
            row = [td.text.strip() for td in tr.find_all('td')]
            rows.append(row)
            
        return pd.DataFrame(rows, columns=headers)
        
    except Exception as e:
        print(f"Error processing {url}: {str(e)}")
        return None


# %% ../nbs/11_deSAPher.ipynb #71d072fb
def get_sap_tables_structure(tables):
    """ Gets structure for multiple SAP tables and combines them into one DataFrame with a column indicating the source table """
    dfs = []
    for table in tables:
        url = get_sap_table_url(table)
        df = get_sap_table_structure(url)
        if df is not None:
            df['Table'] = table
            dfs.append(df)
    
    if not dfs:
        return None
    return pd.concat(dfs, ignore_index=True)

# %% ../nbs/11_deSAPher.ipynb #b11ca26f
def get_sap_table_description(url):
    """
    Scrapes SAP table description from sapdatasheet.org
    Returns None if not found or error occurs
    """
    try:
        import httpx
        from bs4 import BeautifulSoup
        
        response = httpx.get(url)
        response.raise_for_status()
        soup = BeautifulSoup(response.text, 'lxml')
        header = soup.find('div', class_='card-header sapds-card-header')
        
        if header:
            description = header.text.strip()
            return description
            
        return None
        
    except Exception as e:
        print(f"Error getting description from {url}: {str(e)}")
        return None

# %% ../nbs/11_deSAPher.ipynb #968d8f29
def get_sap_tables_structure(tables):
    """ Gets structure for multiple SAP tables and combines them into one DataFrame with a column indicating the source table """
    dfs = []
    for table in tables:
        url = get_sap_table_url(table)
        df = get_sap_table_structure(url)
        if df is not None:
            df['Table'] = table
            df['Table Description'] = get_sap_table_description(url)
            dfs.append(df)
    
    if not dfs:
        return None
    return pd.concat(dfs, ignore_index=True)

# %% ../nbs/11_deSAPher.ipynb #7b67c9fb
sap_to_pandas_dtype = {
    "CLNT": "str",               # Client (typically a 3-character fixed string)
    "CHAR": "str",               # Character-based fields
    "NUMC": "str",               # Numeric character field (stored as a string)
    "DATS": "datetime64[ns]",    # Date field (YYYYMMDD format)
    "CUKY": "str",               # Currency Key
    "CURR": "float64",           # Currency amount (with decimal places)
    "TIMS": "str",               # Time field (HHMMSS format, can be converted to time)
    "QUAN": "float64",           # Quantity field (can include decimal places)
    "UNIT": "str",               # Unit of measure
    "DEC": "float64",            # Decimal field (can also be int if no decimal places)
    "LANG": "str",               # Language key
    "INT2": "int16",             # Small integer (5-digit max)
    "INT4": "int32",             # Standard integer (10-digit max)
    "ACCP": "str",               # Accounting period (stored as a string)
    "RAW": "bytes",              # Raw binary data (e.g., UUIDs)
    "FLTP": "float64"            # Floating-point number
}

# %% ../nbs/11_deSAPher.ipynb #e27587ce
def convert_sap_types(df: pd.DataFrame, sap_sheet: pd.DataFrame) -> pd.DataFrame:
    """
    Converts the columns of the 'df' DataFrame to the correct data types based on 'sap_sheet'.
    
    :param df: Pandas DataFrame containing SAP table data (e.g., "df").
    :param sap_sheet: Pandas DataFrame containing SAP metadata with column data types.
    :return: Converted Pandas DataFrame.
    """
    sap_sheet = sap_sheet.rename(columns=lambda x: x.strip())
    column_type_mapping = sap_sheet.set_index("Field")["DataType"].to_dict()

    for column, sap_type in column_type_mapping.items():
        if column in df.columns:
            pandas_dtype = sap_to_pandas_dtype.get(sap_type, "str")
            try:
                if pandas_dtype == "datetime64[ns]": df[column] = pd.to_datetime(df[column], errors="coerce")
                elif pandas_dtype == "float64": df[column] = pd.to_numeric(df[column], errors="coerce")
                elif pandas_dtype == "int16": df[column] = pd.to_numeric(df[column], errors="coerce").astype("Int16")
                elif pandas_dtype == "int32": df[column] = pd.to_numeric(df[column], errors="coerce").astype("Int32")
                elif pandas_dtype == "bytes": df[column] = df[column].astype("str").apply(lambda x: x.encode() if pd.notna(x) else None)
                else: df[column] = df[column].astype(pandas_dtype)
            except Exception as e:
                print(f"Error converting column {column} to {pandas_dtype}: {e}")
    return df

# %% ../nbs/11_deSAPher.ipynb #64335c5c
def rename_sap_columns(df: pd.DataFrame, sap_sheet: pd.DataFrame) -> pd.DataFrame:
    """
    Renames the columns in the 'df' DataFrame using the 'Short Description' from 'sap_sheet'.
    If a column is not found in 'sap_sheet', it remains unchanged.

    :param df: Pandas DataFrame containing SAP table data (e.g., "df").
    :param sap_sheet: Pandas DataFrame containing SAP metadata with column names and short descriptions.
    :return: DataFrame with renamed columns.
    """
    sap_sheet = sap_sheet.rename(columns=lambda x: x.strip())
    column_name_mapping = sap_sheet.set_index("Field")["Short Description"].to_dict()
    return df.rename(columns=lambda col: column_name_mapping.get(col, col))
