"""Helper to make ETL pipelines easier."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/10_etl.ipynb.

# %% auto #0
__all__ = ['get_demo_data', 'StepMeta', 'format_timedelta', 'print_step_name', 'print_time', 'fill_between_df_parts',
           'print_sample_from_meta_dict', 'display_sample_from_df', 'space_strings', 'print_shape_change',
           'print_step_description', 'print_step_info', 'pipeline', 'track']

# %% ../nbs/10_etl.ipynb #521339ed
import numpy as np
import pandas as pd
from datetime import datetime, timedelta
from time import sleep
from functools import wraps

# %% ../nbs/10_etl.ipynb #9edadacc
def get_demo_data():
    data = {
    'order_id': [101, 102, 103, 104, 105],
    'product': ['Widget A', 'Widget B', 'Widget A', 'Widget C', 'Widget B'],
    'quantity': [50, 30, 75, 20, 45],
    'defects': [2, 1, 3, 0, 2],
    'production_time': [120, 95, 150, 80, 110]  # in minutes
    }
    return pd.DataFrame(data)

# %% ../nbs/10_etl.ipynb #fdb3d687
from datetime import datetime
from time import sleep

# %% ../nbs/10_etl.ipynb #cf3dec25
from dataclasses import dataclass

# %% ../nbs/10_etl.ipynb #61b1a1e4
@dataclass
class StepMeta:
    """Metadata collected for a single ETL pipeline step."""
    
    step_name: str
    """Name of the pipeline step (from function name)."""
    
    step_description: str
    """Description of what this step does (from docstring)."""
    
    in_time: datetime
    """Timestamp when the pipeline step started."""
    
    in_df_shape: tuple
    """Shape (rows, cols) of the input DataFrame."""
    
    in_df_head: pd.DataFrame
    """First 3 rows of the input DataFrame."""
    
    in_df_sample: pd.DataFrame
    """Random sample (up to 5 rows) of the input DataFrame."""
    
    in_df_tail: pd.DataFrame
    """Last 3 rows of the input DataFrame."""
    
    out_time: datetime
    """Timestamp when the pipeline step completed."""
    
    out_df_shape: tuple
    """Shape (rows, cols) of the output DataFrame."""
    
    out_df_head: pd.DataFrame
    """First 3 rows of the output DataFrame."""
    
    out_df_sample: pd.DataFrame
    """Random sample (up to 5 rows) of the output DataFrame."""
    
    out_df_tail: pd.DataFrame
    """Last 3 rows of the output DataFrame."""

    total_time: timedelta
    """Total execution time for this step."""

# %% ../nbs/10_etl.ipynb #1d9df13f
def format_timedelta(td):
    total_seconds = td.total_seconds()
    if total_seconds < 0.001: return f"{total_seconds * 1_000_000:.0f} µs"
    elif total_seconds < 1: return f"{total_seconds * 1000:.2f} ms"
    elif total_seconds < 60: return f"{total_seconds:.2f} s"
    elif total_seconds < 3600: return f"{total_seconds / 60:.2f} min"
    else: return f"{total_seconds / 3600:.2f} h"

# %% ../nbs/10_etl.ipynb #9fd22995
def print_step_name(step_meta: StepMeta): print(15*'*' + ' ' + step_meta.step_name + ' ' + 15*'*')

# %% ../nbs/10_etl.ipynb #85dd0aeb
def print_time(step_meta: StepMeta):
    print(f'Total Time: {format_timedelta(step_meta.total_time)}')
    print('')
    print(f'Start: {step_meta.in_time}')
    print(f'  End: {step_meta.out_time}')

# %% ../nbs/10_etl.ipynb #f6b9028a
def fill_between_df_parts(df):
    return pd.DataFrame(np.nan, index=[''], columns=df.columns).fillna(':')

# %% ../nbs/10_etl.ipynb #cb4c24b4
def print_sample_from_meta_dict(step_meta: StepMeta, mode='in'):
    print(pd.concat(
    [step_meta.in_df_head, 
    fill_between_df_parts(step_meta.in_df_head),
    step_meta.in_df_sample, 
    fill_between_df_parts(step_meta.in_df_head),
    step_meta.in_df_tail]
    ))

# %% ../nbs/10_etl.ipynb #c932d349
def display_sample_from_df(df):
    return pd.concat([
            df.head(3), 
            fill_between_df_parts(df),
            df.sample(min(5, df.shape[0])), 
            fill_between_df_parts(df),
            df.tail(3)]
    )

# %% ../nbs/10_etl.ipynb #b3a7c7d7
def space_strings(strings, total_width):
    gap = (total_width - sum(len(s) for s in strings)) // (len(strings) - 1)
    return (' ' * gap).join(strings)

# %% ../nbs/10_etl.ipynb #4e1641de
def print_shape_change(step_meta: StepMeta):
    in_rows, in_cols = step_meta.in_df_shape
    out_rows, out_cols = step_meta.out_df_shape
    diff_rows, diff_cols = out_rows - in_rows, out_cols - in_cols
    
    diff_rows_str = f"{diff_rows:+d}" if diff_rows != 0 else "0"
    diff_cols_str = f"{diff_cols:+d}" if diff_cols != 0 else "0"
    
    row_width = max(len(str(in_rows)), len(str(out_rows)), len(diff_rows_str))
    col_width = max(len(str(in_cols)), len(str(out_cols)), len(diff_cols_str))
    
    print(
        f"""
        Input:  {in_rows:>{row_width}} rows, {in_cols:>{col_width}} cols
                {' '*row_width}   ↓   {' '*col_width}   ↓
        Diff:   {diff_rows_str:>{row_width}} rows, {diff_cols_str:>{col_width}} cols
                {' '*row_width}   ↓   {' '*col_width}   ↓
        Output: {out_rows:>{row_width}} rows, {out_cols:>{col_width}} cols
        """
        )

# %% ../nbs/10_etl.ipynb #1d6f27bd
def print_step_description(step_meta: StepMeta): print(f"'''{step_meta.step_description}'''")

# %% ../nbs/10_etl.ipynb #b54a0d7b
def print_step_info(step_meta: StepMeta):
    print_step_name(step_meta)
    print_step_description(step_meta)
    print('\n')
    print_time(step_meta)
    print("\nInput DataFrame:")
    print_sample_from_meta_dict(step_meta, mode='in')
    print_shape_change(step_meta)
    print("Output DataFrame:")
    print_sample_from_meta_dict(step_meta, mode='out')
    print('\n')

# %% ../nbs/10_etl.ipynb #418bf70c
def pipeline(df, steps, vrbs_default=True):
    for func, func_kwargs in steps:
        func_kwargs = func_kwargs.copy()
        vrbs =  func_kwargs.get("vrbs", vrbs_default)
        func_kwargs.update({"vrbs": vrbs})
        df = func(df, **func_kwargs)
    return df

# %% ../nbs/10_etl.ipynb #aa7f3599
def track(func):
    @wraps(func)
    def wrapper(in_df, vrbs=False, *args, **kwargs):
        if vrbs:
            # Capture "before" data
            in_time = datetime.now()
            in_df_shape = in_df.shape
            in_df_head = in_df.head(3)
            in_df_sample = in_df.sample(min(in_df.shape[0], 5))
            in_df_tail = in_df.tail(3)
        
        # Run the actual function
        out_df = func(in_df, *args, **kwargs)
        
        if vrbs:
            out_time = datetime.now()
            step_meta = StepMeta(
                step_name=func.__name__,
                step_description=func.__doc__ or "",
                in_time=in_time,
                in_df_shape=in_df_shape,
                in_df_head=in_df_head,
                in_df_sample=in_df_sample,
                in_df_tail=in_df_tail,
                out_time=out_time,
                out_df_shape=out_df.shape,
                out_df_head=out_df.head(3),
                out_df_sample=out_df.sample(min(out_df.shape[0], 5)),
                out_df_tail=out_df.tail(3),
                total_time=out_time - in_time,
            )
            print_step_info(step_meta)
        
        return out_df
    return wrapper
