# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/mis_core',
                'doc_host': 'https://MIS-Analytics.github.io',
                'git_url': 'https://github.com/MIS-Analytics/mis_core',
                'lib_path': 'mis_core'},
  'syms': {'mis_core.core': {'mis_core.core.move_columns': ('core.html#move_columns', 'mis_core/core.py')}}}
