"""Universal helper functions"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto #0
__all__ = ['move_columns', 'clean_string', 'clean_col_names']

# %% ../nbs/00_core.ipynb #f2023e00
import pandas as pd

# %% ../nbs/00_core.ipynb #858a00a6
def move_columns(
    df: pd.DataFrame,  # Input
    cols_to_move: str,  # Single 
    pos: int  # Target
) -> pd.DataFrame:
    """
    Move one or more columns to a specified position in a DataFrame.
    """

    if isinstance(cols_to_move, str):
        cols_to_move = [cols_to_move]

    cols = list(df.columns)

    for c in cols_to_move:
        cols.remove(c)

    new_cols = cols[:pos] + cols_to_move + cols[pos:]
    return df[new_cols]


# %% ../nbs/00_core.ipynb #8b6f1ad2
def clean_string(input_string:str):
    """Cleans input_string"""
    processed_string = "".join(c if c.isalnum() else "_" for c in input_string.lower()).strip("_")
    return "_".join(filter(None, processed_string.split("_")))

# %% ../nbs/00_core.ipynb #dce9f5bd
def clean_col_names(df:pd.DataFrame) -> pd.DataFrame:
    """Returns df with clean column names by using `clean_string` on each column name."""
    df.columns = [clean_string(col.lower()) for col in df.columns]
    return df
