"""Fill in a module description here"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto #0
__all__ = ['move_columns']

# %% ../nbs/00_core.ipynb #f2023e00
import pandas as pd

# %% ../nbs/00_core.ipynb #858a00a6
def move_columns(
    df: pd.DataFrame,  # Input
    cols_to_move: str,  # Single 
    pos: int  # Target
) -> pd.DataFrame:
    """
    Move one or more columns to a specified position in a DataFrame.
    """

    # Ensure `cols_to_move` is always a list
    if isinstance(cols_to_move, str):
        cols_to_move = [cols_to_move]

    cols = list(df.columns)

    # Remove the columns to be moved from the current order
    for c in cols_to_move:
        cols.remove(c)

    # Insert the removed columns after the specified position
    new_cols = cols[:pos] + cols_to_move + cols[pos:]

    # Return the reordered DataFrame
    return df[new_cols]

